## Spring DATASOURCE (DataSourceAutoConfiguration & DataSourceProperties)
spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/shop_api
#    username: root
#    password: root
    url: jdbc:mysql://eu-cdbr-west-03.cleardb.net/heroku_101b57c2b4e1c68?reconnect=true
    username: b0adc30ddca70c
    password: c23f7aae
    platform: MYSQL
    initialization-mode: always
    continue-on-error: false
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: validate
    database: mysql
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false;
    database-platform: org.hibernate.dialect.MySQL5Dialect
  #      dialect: org.hibernate.dialect.MySQL5Dialect

#  jackson:
#    default-property-inclusion: non_null
#  redis:
#    host: localhost
#    port: 6379
#  freemarker:
#      cache: false




  queries:
    users-query: select email, password, active from users where email=?
    roles-query: select email, role from users where email=?
server:
  port: ${PORT:8080}
  servlet:
    contextPath: /api

jwtSecret: me.zhulin
jwtExpiration: 86400
